version: '3'

services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_DB: otus_hw7
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: